### PR TITLE
Sync `define_super_struct.rkt` for Exercise 7

### PR DESCRIPTION
**Pull request by shhyou**
The `define_super_struct.rkt` file in Exercise 7 is behind its counterpart in the solution folder. This PR copies the `define_super_struct.rkt` file over.

This change is a low priority. It does not affect the exercise and can be merged after the deadline.

Concretely, `define_super_struct.rkt` from the solution folder contains struct information for the ones used in the exercise (L825--L852). As such, users will get warning about incorrect field names and incorrect field order.

```
> (define-struct (multiple-choice-question question) (number-of-choice))
define-struct: the structure multiple-choice-question has missing fields: number-of-choices

> (define-struct numeric-question (range))
define-struct: expected a structure definition with the super struct question
  given: no super struct
```

### CODE REVIEW

**Comment by shhyou** [comment]
Thanks a lot for the follow up!

I wish to add that L825--L852 are only relevant to exercise 7 and not other parts.
That is, I think this code only needs to appear in the `define_super_struct.rkt` for exercise 7:

```racket
#| expected struct declarations for exercise 7 |#
(provide
 struct-spec:question
 struct-spec:multiple-choice-question
 struct-spec:numeric-question
 display
 check-answer)
...
(define-struct-name-specification numeric-question
  #:super question
  #:fields (error-range)
  #:override-or-new-methods (check-answer)
  #:allowed-methods (display check-answer))
```

**Comment by bainco** [comment]
> I wish to add that L825--L852 are only relevant to exercise 7 and not other parts. That is, I think this code only needs to appear in the `define_super_struct.rkt` for exercise 7:

They're not conflicting though are they? I think it might be better to just have the exact same file across all instances.

**Comment by shhyou** [comment]
Depends on the configuration, those declarations could change the warning. For example, `asteroids_lib.rkt` enables these two warnings:
```racket
(check-define-struct:warn-not-allowed-method? #t)
(check-define-struct:warn-unspecified-struct? #t)
```
as such, if L825--L852 are present, there will be warnings for unspecified structs:
```racket
> (define-struct myposn (x y))
define-struct warning: expected a structure definition specified in the assignment
  given: (define-struct myposn (x y) ...)
```
I think it makes sense to rename the ones used in exercise 7, or it'll also be good to separate L825--L852 into something like `quiz_lib.rkt`. That way e7 can also enable the same two warnings as the asteroids lib.

**Comment by bainco** [comment]
> I think it makes sense to rename the ones used in exercise 7, or it'll also be good to separate L825--L852 into something like `quiz_lib.rkt`. That way e7 can also enable the same two warnings as the asteroids lib.

Understood. I'm loathe to separate it out...but I think that's probably the best option (it then matches the format of the other assignments, `snake_lib`, `asteroids_lib` etc.

**Pull request closed without merging**
